### ISSUE TITLE
Datum bei Blogeinträgen

### ISSUE THREAD

**Issue by jpunke** [weitblicker/weitblickapp-android-v2#49]
Wenn Blogeinträge einen Teaser-text besitzen, rutscht das Datum in diesen Text hinein
<img width="177" alt="SEP-Weitblick" src="https://user-images.githubusercontent.com/33029581/70717447-a25cb400-1cee-11ea-838f-f5a53af9cf48.PNG">

**Comment by ilkawntr** [comment]
Ich glaube ist gefixed kann es halt jetzt nur nicht testen

**Comment by jpunke** [comment]
Ist gefixt!
